name: Release
on:
  push:
    tags: ['*']

jobs:
  release:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Create release
        uses: taiki-e/create-gh-release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
  upload:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Upload binary
        uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: geologs
          archive: $bin_$tag_$target
          token: ${{ secrets.GITHUB_TOKEN }}
